fq:
  api:
    base-url: https://api5-normal-sinfonlineb.fqnovel.com
    cookie: store-region=cn-zj; store-region-src=did; install_id=670078579016233;
    device:
      aid: '1967'
      cdid: '1ac503b0-919b-417b-8817-b3a438f129aa'
      device-brand: 'Xiaomi'
      device-id: '7497458396288120'
      device-type: '23127PN0CC'
      dpi: '480'
      host-abi: arm64-v8a
      install-id: '7458454191200779'
      resolution: '2400*1080'
      rom-version: 'V417IR+release-keys'
      update-version-code: '68132'
      version-code: '68132'
      version-name: 6.8.1.32
    user-agent: com.dragon.read.oversea.gp/68132 (Linux; U; Android 13; zh_CN; 23127PN0CC;
      Build/V417IR;tt-ok/3.12.13.4-tiktok)